server:
  port: 8088

spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:~/inflearn1
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        highlight_sql: true
    defer-datasource-initialization: true #Hibernate 가 먼저 테이블을 만들게 해주는 것

logging:
  level:
    org:
      springframework: DEBUG
    hibernate: DEBUG

  messages:
    basename: messages #우리가 사용할 메시지 파일(다국어 파일)의 이름을 'messages'라고 저장하는 것
    #'리소스 폴더'-->'messages.properties'를 만들어준다. 여기서 'messages'는 바로 여기 'yml 파일'에서 작성한
    #'basename: messages'의 'messages'와 동일하게 해줘야 함!



  devtools:
    livereload:
      enabled: true



  #시큐리티 적용한 후에 로컬호스트 접속할 때 입력해야 하는 'name'과 'password'를 여기서 내가 임의로 지정할 수 있음
  #포스트맨에서 'Authorization 탭' --> 'Basic Auth' --> 옆에 'Username과 password'에 아래 정보 입력하면 됨
  #단, '클래스 SecurityConfig 내부 로직들 중'에서 'withUser'와 'password'에 따로 더 작성해둔 것이 있으면,
  #로그인 할 때 아래가 아니라 그것을 따라감
  security:
    user:
      name: username
      password: pwdpwd



#'Actuator' 관련 설정내용
management:
  endpoints:
    web:
      exposure:
        include: "*"








